name: Build make-flagslowfix

on:
  push:
    branches:
      - main        # build on every commit to main
    tags:
      - '*'         # build on every tag
  pull_request:     # optional: build on PRs
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up C++ environment
        uses: actions/setup-gcc@v1

      - name: Create build directory
        run: mkdir -p build

      - name: Compile make-flagslowfix
        run: g++ -O2 -march=native -Wall -Wextra -std=c++17 src/main.cpp -o build/make-flagslowfix

      - name: Package tar.gz
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          [ -z "$VERSION" ] && VERSION="latest"
          tar czf build/make-flagslowfix-${VERSION}.tar.gz -C build make-flagslowfix

      - name: Package tar.xz
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          [ -z "$VERSION" ] && VERSION="latest"
          tar cJf build/make-flagslowfix-${VERSION}.tar.xz -C build make-flagslowfix

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: make-flagslowfix-artifacts
          path: |
            build/make-flagslowfix
            build/make-flagslowfix-*.tar.gz
            build/make-flagslowfix-*.tar.xz
